[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mongodb', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-scripts --no-interaction'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'